<robot name="create_robot" xmlns:xacro="http://wiki.ros.org/xacro">
    <xacro:property name="base_footprint_radius" value="0.00001"/>

    <link name="base_footprint">
        <visual>
            <geometry>
                <sphere radius="${base_footprint_radius}"/>
            </geometry>
        </visual>
    </link>

    <xacro:property name="base_link_radius" value="0.1"/>
    <xacro:property name="base_link_length" value="0.08"/>
    <xacro:property name="to_ground" value="0.015"/>
    <xacro:property name="base_joint_z" value="${base_link_length/2+to_ground}"/>

    <link name="base_link">
        <visual>
            <geometry>
                <cylinder radius="${base_link_radius}" length="${base_link_length}"/>
            </geometry>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <material name="base_link_color">
                <color rgba="1 1 0.1 0.5"/>
            </material>
        </visual>
        <collision>
            <geometry>
                <cylinder radius="${base_link_radius}" length="${base_link_length}"/>
            </geometry>
            <origin xyz="0 0 0" rpy="0 0 0"/>
        </collision>
        <inertial>
            <mass value="1"/>
            <inertia ixx="${(1*(3*base_link_radius*base_link_radius)+base_link_length*base_link_length)/12}" iyy="${(1*(3*base_link_radius*base_link_radius)+base_link_length*base_link_length)/12}" izz="${(1*base_link_radius*base_link_radius)/2}" ixy="0" iyz="0" ixz="0"/>
        </inertial>
    </link>

    <joint name="baseToFootprint" type="fixed">
        <parent link="base_footprint"/>
        <child link="base_link"/>
        <origin xyz="0 0 ${base_joint_z}" rpy="0 0 0"/>
    </joint>

    <link name="left_wheel">
        <visual>
            <geometry>
                <cylinder radius="0.0325" length="0.015"/>
            </geometry>
            <origin xyz="0 0 0" rpy="1.57 0 0"/>
            <material name="left_wheel_color">
                <color rgba="0 0 0 1"/>
            </material>
        </visual>
        <collision>
            <geometry>
                <cylinder radius="0.0325" length="0.015"/>
            </geometry>
            <origin xyz="0 0 0" rpy="1.57 0 0"/>
        </collision>
        <inertial>
            <mass value="0.2"/>
            <inertia ixx="${(0.2*(3*0.0325*0.0325)+0.015*0.015)/12}" iyy="${(0.2*(3*0.0325*0.0325)+0.015*0.015)/12}" izz="${(0.2*0.0325*0.0325)/2}" ixy="0" iyz="0" ixz="0"/>
        </inertial>
    </link>


    <joint name="left_wheelToBase" type="continuous">
        <parent link="base_link"/>
        <child link="left_wheel"/>
        <origin xyz="0 0.1 -0.0225" rpy="0 0 0"/>
        <axis xyz="0 1 0"/>
    </joint>

    <link name="right_wheel">
        <visual>
            <geometry>
                <cylinder radius="0.0325" length="0.015"/>
            </geometry>
            <origin xyz="0 0 0" rpy="1.57 0 0"/>
            <material name="left_wheel_color">
                <color rgba="0 0 0 1"/>
            </material>
        </visual>
        <collision>
            <geometry>
                <cylinder radius="0.0325" length="0.015"/>
            </geometry>
            <origin xyz="0 0 0" rpy="1.57 0 0"/>
        </collision>
        <inertial>
            <mass value="0.2"/>
            <inertia ixx="${(0.2*(3*0.0325*0.0325)+0.015*0.015)/12}" iyy="${(0.2*(3*0.0325*0.0325)+0.015*0.015)/12}" izz="${(0.2*0.0325*0.0325)/2}" ixy="0" iyz="0" ixz="0"/>
        </inertial>
    </link>


    <joint name="right_wheelToBase" type="continuous">
        <parent link="base_link"/>
        <child link="right_wheel"/>
        <origin xyz="0 -0.1 -0.0225" rpy="0 0 0"/>
        <axis xyz="0 1 0"/>
    </joint>

    <link name="front_wheel">
        <visual>
            <geometry>
                <sphere radius="0.0075"/>
            </geometry>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <material name="front_wheel_color">
                <color rgba="0 0 0 0.8"/>
            </material>
        </visual>
        <collision>
            <geometry>
                <sphere radius="0.0075"/>
            </geometry>
            <origin xyz="0 0 0" rpy="0 0 0"/>
        </collision>
        <inertial>
            <mass value="0.05"/>
            <inertia ixx="${2*0.05*0.0075*0.0075/5}" iyy="${2*0.05*0.0075*0.0075/5}" izz="${2*0.05*0.0075*0.0075/5}" ixy="0" iyz="0" ixz="0"/>
        </inertial>
    </link>

    <joint name="front_wheelToBase" type="continuous">
        <parent link="base_link"/>
        <child link="front_wheel"/>
        <origin xyz="0.08 0 -0.0475" rpy="0 0 0"/>
        <axis xyz="1 1 1"/>
    </joint>

    <link name="back_wheel">
        <visual>
            <geometry>
                <sphere radius="0.0075"/>
            </geometry>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <material name="front_wheel_color">
                <color rgba="0 0 0 0.8"/>
            </material>
        </visual>
        <collision>
            <geometry>
                <sphere radius="0.0075"/>
            </geometry>
            <origin xyz="0 0 0" rpy="0 0 0"/>
        </collision>
        <inertial>
            <mass value="0.05"/>
            <inertia ixx="${2*0.05*0.0075*0.0075/5}" iyy="${2*0.05*0.0075*0.0075/5}" izz="${2*0.05*0.0075*0.0075/5}" ixy="0" iyz="0" ixz="0"/>
        </inertial>
    </link>
    <joint name="back_wheelToBase" type="continuous">
        <parent link="base_link"/>
        <child link="back_wheel"/>
        <origin xyz="-0.08 0 -0.0475" rpy="0 0 0"/>
        <axis xyz="1 1 1"/>
    </joint>
</robot>