<robot name="create_robot" xmlns:xacro="http://wiki.ros.org/xacro">
    <xacro:property name="link_x" value="0.02"/>
    <xacro:property name="link_y" value="0.05"/>
    <xacro:property name="link_z" value="0.05"/>
    <xacro:property name="joint_x" value="0.08"/>
    <xacro:property name="joint_y" value="0"/>
    <xacro:property name="joint_z" value="${base_link_length/2 + link_z/2}"/>

    <link name="camera">
        <visual>
            <geometry>
                <box size="${link_x} ${link_y} ${link_z}"/>
            </geometry>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <material name="camera">
                <color rgba="0.5 0.5 0.5 1"/>
            </material>
        </visual>
    </link>

    <gazebo reference="camera">
        <sensor type="camera" name="camera1">
            <update_rate>30.0</update_rate>
            <camera name="head">
                <horizontal_fov>1.3962634</horizontal_fov>
                <image>
                    <width>1920</width>
                    <height>1080</height>
                    <format>R8G8B8</format>
                </image>
                <clip>
                    <near>0.02</near>
                    <far>300</far>
                </clip>
                <noise>
                    <type>gaussian</type>
                    <!-- Noise is sampled independently per pixel on each frame.
                         That pixel's noise value is added to each of its color
                         channels, which at that point lie in the range [0,1]. -->
                    <mean>0.0</mean>
                    <stddev>0.007</stddev>
                </noise>
            </camera>
            <plugin name="camera_controller" filename="libgazebo_ros_camera.so">
                <alwaysOn>true</alwaysOn>
                <updateRate>0.0</updateRate>
                <cameraName>camera1</cameraName>
                <imageTopicName>image_raw</imageTopicName>
                <cameraInfoTopicName>camera_info</cameraInfoTopicName>
                <frameName>camera</frameName>
                <hackBaseline>0.07</hackBaseline>
                <distortionK1>0.0</distortionK1>
                <distortionK2>0.0</distortionK2>
                <distortionK3>0.0</distortionK3>
                <distortionT1>0.0</distortionT1>
                <distortionT2>0.0</distortionT2>
            </plugin>
        </sensor>
    </gazebo>

    <joint name="camera_to_base" type="fixed">
        <parent link="base_link"/>
        <child link="camera"/>
        <origin xyz="${joint_x} ${joint_y} ${joint_z}" rpy="0 0 0"/>
    </joint>
</robot>